### ISSUE TITLE
On unsupported hardware, application remains blank

### ISSUE THREAD

**Issue by brs17** [pop-os/firmware-manager#36]
ISSUE: 
Looking at the firmware tab in GNOME Control Center on 19.04 on a machine without any supported System76 or fwupd supported devices the firmware panel remains blank.

![Screenshot from 2019-08-15 22-16-05](https://user-images.githubusercontent.com/7460774/63143187-4be2a180-bfaa-11e9-919b-7cd39a98c62f.png)

HYPOTHESIS: It appears that the search for fwupd devices begins, as evident by the `scanning fwupd devices` message. The search never appears to end (perhaps because `TIMEOUT=-1` in fwupd-dbus/src/lib.rs ?) and therefore the `view_empty` state is never reached and the panel remains blank.

**Comment by mmstick** [comment]
That could be what's happening, but if so, that would be an issue with the fwupd daemon holding the connection because it got stuck, and therefore isn't closing the socket, and then won't be able to respond to any future requests.

I will check if it could be an issue with the "No devices" view simply never getting shown. I will also add a debug message so that you can see if the fwupd connection has cleanly exited.

**Comment by mmstick** [comment]
It would seem that I never wrote the code that sends `FirmwareSignal::ScanningComplete` back to the main thread, so the UI continued to assume that updates were still being scanned.

**Comment by brs17** [comment]
This appears to still be an issue even after applying the appropriate patch.

**Comment by mmstick** [comment]
I got it working again.
